# Generated by Django 4.2.13 on 2024-05-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notey", "0002_note_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
    ]
